server:
  port: 8085
  servlet:
    encoding:
      enabled: true # 大模型对话中文乱码处理
      force: true
      charset: Utf-8

spring:
  application:
    name: Embedding1
  ai:
    dashscope:
      api-key: xxx
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3.5:4b
      embedding:
        options:
          model: qwen3-embedding:0.6b
